### ISSUE TITLE
TODO: Remove unused imports that slow us down

### ISSUE THREAD

**Issue by cclauss** [khabdrick/Workout-progress-tracker#6]
It can be a performance hit to import files that we do not use.
- [ ] Remove the [`F401` test](https://github.com/khabdrick/Workout-progress-tracker/blob/main/.github/workflows/lint_python.yml#L13) from flake8 ignore 
- [ ] Run flake8 and remove the imports to speed thing up
- [ ] Test the site to ensure that none of the imports removed were used for their side-effect.
